from cs285.util.cls import SupervisionMode

DEFAULT_CONFIG = dict(
    do_dagger=False,
    num_agent_train_steps_per_iter=1000,
    n_iter=1,
    batch_size=1000,
    eval_batch_size=1000,
    train_batch_size=100,
    n_layers=2,
    size=64,
    learning_rate=5e-3,
    video_log_freq=-1,
    scalar_log_freq=1,
    no_gpu=False,
    which_gpu=0,
    max_replay_buffer_size=1000000,
    save_params=False,
    seed=1,
    data_path='../../data',
    siren=False,
    omega=30,
    supervision_mode=SupervisionMode.VALUE_ONLY,
    epsilon_s=0.05,
    train_separate_params=False,
    offset_learning_rate=5e-3,
    gradient_loss_scale=1.0,
    additional_activation='identity',
    auto_cast=False,
    ep_len=0,
)
